#    消费者的端口和上下文根
server:
  port: 8082
  servlet:
    context-path: /p2p
#    配置字符过滤器为UTF-8
    encoding:
      charset: UTF-8
      force: true
      enabled: true

#    配置dubbo的名称和注册中心地址
dubbo:
  application:
    name: p2p-web
  registry:
    address: zookeeper://127.0.0.1:2181


#     配置thymeleaf的缓存机制，使用字符集名，类型
spring:
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML
#    thymeleaf视图解析器，可不定义
    prefix: classpath:/templates/
    suffix: .html
#     HiddenHttpMethodFilter过滤器，支持把post请求转为put或delete请求
  mvc:
    hiddenmethod:
      filter:
        enabled: true
#    配置redis的地址和端口
    redis:
      host: 127.0.0.1
      port: 6379
